baseURL = "http://longxianwen.net/"
languageCode = "en-us"
title = "Xianwen Long"
theme = "tale"
[menu]
#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     title = "About"
#     url = "/about/"
#     weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0